x-constants:
  backend_host: &backend_host localhost
  backend_port: &backend_port 5000

services:
  frontend:
    image: smpolito/geocontrolui:latest
    container_name: geocontrol-frontend
    ports:
      - "5173:5173" # Anchored variables defined above (e.g., &frontend_port) cannot be used within quoted strings.
        # Values like port numbers must be written explicitly as literals, but they should remain consistent with the defined variables.
    volumes: # Environment variables for the front-end must be defined in the frontend/env.vars.json and the file must be
      - ./frontend/env-vars.json:/app/dist/config.json # explicitly mounted in the container to be effective


  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    container_name: geocontrol-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=geocontrol_db
      - DB_USERNAME=geocontrol_user
      - DB_PASSWORD=secret
      - LOG_LEVEL=info
      - LOG_PATH=logs
      - ERROR_LOG_FILE=error.log
      - COMBINED_LOG_FILE=combined.log
      # aggiungi qui altre variabili se richieste da config.ts
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: geocontrol-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geocontrol_db
      MYSQL_USER: geocontrol_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data: